root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main" 
  cmd = "go build -o tmp/main ./cmd/server/main.go"
  args_bin = ["run"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "tmp"]
  delay = 1000

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear = true 
[proxy]
  enabled = true
  app_port = 8080
