# Archivo de configuración para Air
root = "." # Directorio raíz del proyecto
tmp_dir = "tmp" # Directorio temporal para builds

[build]
  bin = "tmp/main" # Archivo binario temporal
  cmd = "go build -o tmp/main ./cmd/server/main.go" # Comando para compilar
  include_ext = ["go", "tpl", "tmpl", "html"] # Archivos a observar para cambios
  exclude_dir = ["vendor", "tmp"] # Directorios a ignorar
  delay = 1000 # Milisegundos antes de reiniciar

[log]
  time = true # Mostrar timestamps en logs

[misc]
# Delete tmp directory on exit
  clean_on_exit = true

[screen]
  clear = true # Limpiar la pantalla en cada reinicio
[proxy]
  enabled = true
  app_port = 8080
