services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.config/sops/age/keys.txt:/keys/age.txt:ro
    environment:
      ENV: "debug"
      MD_RUNTIME: docker
      MD_RECONCILE_SCRIPT: /app/scripts/reconcile.sh
      SOPS_AGE_KEY_FILE: /keys/age.txt
    container_name: magos-dominus
    command: ["air", "-c", ".air.toml"]

