name: Build & Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  BINARY: magos-dominus
  MAIN_PKG: ./cmd/server

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: "1.25.x" }

      - name: Build
        run: |
          mkdir -p dist
          EXT=""
          [ "${{ matrix.goos }}" = "windows" ] && EXT=".exe"
          VERSION="${GITHUB_REF_NAME:-dev}"
          COMMIT="${GITHUB_SHA}"
          DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          LDFLAGS="-s -w \
            -X github.com/jpvargasdev/magos-dominus/internal/cli.version=$VERSION \
            -X github.com/jpvargasdev/magos-dominus/internal/cli.commit=$COMMIT \
            -X github.com/jpvargasdev/magos-dominus/internal/cli.date=$DATE"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 \
            go build -trimpath -ldflags "$LDFLAGS" \
            -o "dist/${{ env.BINARY }}-${{ matrix.goos }}-${{ matrix.goarch }}${EXT}" \
            ${{ env.MAIN_PKG }}

      - name: Upload artifact (unique per OS/ARCH)
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.BINARY }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          path: dist/*
          if-no-files-found: error
          compression-level: 0

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > SHA256SUMS.txt
          ls -lh

      - name: Create GitHub Release & upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Binaries for ${{ github.ref_name }}.
            See SHA256SUMS.txt for checksums.
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
