name: Build binaries

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:   [linux, darwin, windows]
        goarch: [amd64, arm64]
    env:
      MAIN_PKG: ./cmd/server        
      BINARY: magos-dominus
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Print Go env
        run: go env

      - name: Build
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi

          # version info 
          VERSION="${GITHUB_REF_NAME:-dev}"
          COMMIT="${GITHUB_SHA}"
          DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          LDFLAGS="-s -w -X main.version=$VERSION -X main.commit=$COMMIT -X main.date=$DATE"

          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -trimpath -ldflags "$LDFLAGS" -o "dist/${{ env.BINARY }}-${{ matrix.goos }}-${{ matrix.goarch }}${EXT}" $MAIN_PKG

      - name: Checksums
        run: |
          cd dist
          shasum -a 256 * > SHA256SUMS.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.BINARY }}-${{ github.ref_name || 'dev' }}"
          path: dist/*
          if-no-files-found: error
